// Licence file format, shared by the product and the Vayrone License Server.
// This module is pure (node:crypto only) so the License Server can use it
// without the mail engine.
//
//   envelope = { format, kid, payload: base64url(JSON bytes), sig: base64url }
//   sig      = Ed25519( "<format>\n<payload>" )
//
// The signature covers the payload bytes exactly as issued, so no JSON
// canonicalisation is needed. The format string is part of the signed message:
// a heartbeat revocation can never be replayed as a licence, and so on.
// Files are ASCII-armoured so they survive email and copy/paste.
import { createPrivateKey, createPublicKey, generateKeyPairSync, randomBytes, sign, verify, type KeyObject } from 'node:crypto';

export const LICENSE_FORMAT = 'vpm-license/1';
export const REVOCATION_FORMAT = 'vpm-revocation/1';
export const INTEGRITY_FORMAT = 'vpm-integrity/1';
export const REQUEST_FORMAT = 'vpm-request/1';
export const UPDATE_FORMAT = 'vpm-update/1';
export const UPDATE_INDEX_FORMAT = 'vpm-update-index/1';
export type SignedFormat = typeof LICENSE_FORMAT | typeof REVOCATION_FORMAT | typeof INTEGRITY_FORMAT | typeof UPDATE_FORMAT | typeof UPDATE_INDEX_FORMAT;

export const COMPONENTS = ['os', 'board', 'uuid', 'disk', 'cpu'] as const;
export type ComponentName = (typeof COMPONENTS)[number];
/** Hashed hardware/OS identifiers; null when the machine does not expose one. */
export type Components = Record<ComponentName, string | null>;

/** Feature flags a licence can carry. Unknown flags are kept and ignored. */
export const FEATURES = ['archive', 'backup_cloud', 'antivirus', 'support_access', 'journaling', 'external_fetch'] as const;

export interface LicensePayload {
  format: typeof LICENSE_FORMAT;
  product: 'postmaster';
  licenseId: string;
  /** Last five characters of the licence key, for display. */
  keyHint: string;
  client: { name: string; contact?: string | null; email?: string | null; phone?: string | null; city?: string | null; gstin?: string | null };
  reseller: { name: string } | null;
  plan: { code: string; name: string };
  maxUsers: number;
  maxExternalAccounts: number | null;
  features: string[];
  /** License Server clock at signing; also a lower bound for this machine's clock. */
  issuedAt: string;
  /** Subscription end; null for a perpetual licence. */
  expiresAt: string | null;
  amcExpiresAt: string | null;
  /** The install must re-validate (heartbeat or offline file) before this time. */
  checkBy: string;
  /** How often an online install calls the heartbeat endpoint. */
  heartbeatHours: number;
  activation: { id: string; mode: 'online' | 'offline'; machineId: string; components: Components };
}

export interface RevocationPayload {
  format: typeof REVOCATION_FORMAT;
  licenseId: string;
  activationId: string;
  reason: 'transferred' | 'suspended' | 'revoked';
  message: string;
  issuedAt: string;
}

export interface IntegrityPayload {
  format: typeof INTEGRITY_FORMAT;
  version: string;
  /** Relative path (forward slashes) → sha256 hex. */
  files: Record<string, string>;
  issuedAt: string;
}

/** Activation request: generated by an offline install, processed by the portal. Not signed. */
export interface RequestPayload {
  format: typeof REQUEST_FORMAT;
  /** First activation: the licence key. Re-validation: the current licence id. */
  key: string | null;
  licenseId: string | null;
  machine: { id: string; components: Components };
  product: { version: string; installId: string; hostname: string; site?: { company: string; gstin: string | null; contact: string | null; phone: string | null; email: string | null; address: string | null } | null };
  usage: { activeUsers: number; externalAccounts: number };
  createdAt: string;
  nonce: string;
}

export interface Envelope {
  format: SignedFormat;
  kid: string;
  payload: string;
  sig: string;
}

export class LicenseFormatError extends Error {
  constructor(
    message: string,
    readonly code: 'MALFORMED' | 'UNKNOWN_KEY' | 'BAD_SIGNATURE' | 'WRONG_TYPE' = 'MALFORMED',
  ) {
    super(message);
  }
}

const ARMOR: Record<SignedFormat | typeof REQUEST_FORMAT, string> = {
  [LICENSE_FORMAT]: 'VAYRONE POSTMASTER LICENSE',
  [REVOCATION_FORMAT]: 'VAYRONE POSTMASTER REVOCATION',
  [INTEGRITY_FORMAT]: 'VAYRONE POSTMASTER INTEGRITY',
  [UPDATE_FORMAT]: 'VAYRONE POSTMASTER UPDATE',
  [UPDATE_INDEX_FORMAT]: 'VAYRONE POSTMASTER UPDATE INDEX',
  [REQUEST_FORMAT]: 'VAYRONE POSTMASTER ACTIVATION REQUEST',
};

export function armor(kind: keyof typeof ARMOR, body: string): string {
  const b64 = Buffer.from(body, 'utf8').toString('base64');
  return `-----BEGIN ${ARMOR[kind]}-----\n${b64.replace(/.{1,64}/g, '$&\n')}-----END ${ARMOR[kind]}-----\n`;
}

export function unarmor(kind: keyof typeof ARMOR, text: string): string {
  const label = ARMOR[kind];
  const m = new RegExp(`-----BEGIN ${label}-----([\\s\\S]*?)-----END ${label}-----`).exec(text);
  if (m) return Buffer.from(m[1]!.replace(/\s+/g, ''), 'base64').toString('utf8');
  if (text.trim().startsWith('{')) return text.trim(); // bare JSON (API responses)
  throw new LicenseFormatError(`This is not a ${label.toLowerCase().replace('vayrone postmaster ', '')} file`, 'WRONG_TYPE');
}

function message(format: string, payload: string): Buffer {
  return Buffer.from(`${format}\n${payload}`, 'utf8');
}

export function signDoc<T extends { format: SignedFormat }>(payload: T, privateKey: KeyObject | string, kid: string): string {
  const key = typeof privateKey === 'string' ? createPrivateKey(privateKey) : privateKey;
  const p = Buffer.from(JSON.stringify(payload), 'utf8').toString('base64url');
  const env: Envelope = { format: payload.format, kid, payload: p, sig: sign(null, message(payload.format, p), key).toString('base64url') };
  return armor(payload.format, JSON.stringify(env));
}

/** Public keys by key id (PEM, SPKI). */
export type KeyRing = Record<string, string>;

export function verifyDoc<T extends { format: SignedFormat }>(format: T['format'], text: string, keys: KeyRing): { payload: T; kid: string } {
  let env: Envelope;
  try {
    env = JSON.parse(unarmor(format, text)) as Envelope;
  } catch (e) {
    if (e instanceof LicenseFormatError) throw e;
    throw new LicenseFormatError('The file is damaged (not valid JSON)');
  }
  if (!env || typeof env.payload !== 'string' || typeof env.sig !== 'string' || typeof env.kid !== 'string') throw new LicenseFormatError('The file is damaged');
  if (env.format !== format) throw new LicenseFormatError(`Expected a ${format} document, got ${String(env.format)}`, 'WRONG_TYPE');
  const pem = keys[env.kid];
  if (!pem) throw new LicenseFormatError(`The file was signed with an unknown key (${env.kid})`, 'UNKNOWN_KEY');
  const ok = verify(null, message(format, env.payload), createPublicKey(pem), Buffer.from(env.sig, 'base64url'));
  if (!ok) throw new LicenseFormatError('The signature is not valid; the file was altered or not issued by Vayrone', 'BAD_SIGNATURE');
  const payload = JSON.parse(Buffer.from(env.payload, 'base64url').toString('utf8')) as T;
  if (payload.format !== format) throw new LicenseFormatError('Signed payload type mismatch', 'WRONG_TYPE');
  return { payload, kid: env.kid };
}

export function encodeRequest(r: RequestPayload): string {
  return armor(REQUEST_FORMAT, JSON.stringify(r));
}

export function decodeRequest(text: string): RequestPayload {
  let r: RequestPayload;
  try {
    r = JSON.parse(unarmor(REQUEST_FORMAT, text)) as RequestPayload;
  } catch (e) {
    if (e instanceof LicenseFormatError) throw e;
    throw new LicenseFormatError('The request file is damaged');
  }
  if (r?.format !== REQUEST_FORMAT || !r.machine?.components || !r.machine.id) throw new LicenseFormatError('The request file is damaged');
  if (!r.key && !r.licenseId) throw new LicenseFormatError('The request file has neither a licence key nor a licence id');
  return r;
}

export function newNonce(): string {
  return randomBytes(12).toString('base64url');
}

/** Ed25519 key pair as PEM strings (License Server key generation, tests). */
export function generateSigningKey(): { privateKey: string; publicKey: string } {
  const { privateKey, publicKey } = generateKeyPairSync('ed25519');
  return { privateKey: privateKey.export({ type: 'pkcs8', format: 'pem' }).toString(), publicKey: publicKey.export({ type: 'spki', format: 'pem' }).toString() };
}

// ---------------------------------------------------------------- keys
// VPM-XXXXX-XXXXX-XXXXX-XXXXX-C: 20 random Crockford base32 characters plus a
// check character, so typing mistakes are caught before any network call.
const B32 = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';

function checkChar(body: string): string {
  let sum = 0;
  for (let i = 0; i < body.length; i++) sum = (sum * 31 + B32.indexOf(body[i]!) + 1) % 1_000_003;
  return B32[sum % 32]!;
}

export function generateLicenseKey(): string {
  const bytes = randomBytes(20);
  const body = [...bytes].map((b) => B32[b & 31]).join('');
  return `VPM-${body.match(/.{5}/g)!.join('-')}-${checkChar(body)}`;
}

/** Normalises user input (case, O/0, I/L/1, spaces). Returns null when the key is not well formed. */
export function normalizeLicenseKey(input: string): string | null {
  const s = input.toUpperCase().replace(/[\s-]/g, '').replace(/O/g, '0').replace(/[IL]/g, '1').replace(/U/g, 'V');
  const m = /^VPM([0-9A-Z]{20})([0-9A-Z])$/.exec(s);
  if (!m || [...m[1]!].some((c) => !B32.includes(c))) return null;
  if (checkChar(m[1]!) !== m[2]) return null;
  return `VPM-${m[1]!.match(/.{5}/g)!.join('-')}-${m[2]}`;
}
