/// <reference path="./types/shims.d.ts" />
export * from './config.js';
export * from './context.js';
export * from './service.js';
export * from './migrate.js';
export { MailStore, StoreError, normalizePath } from './store/mailstore.js';
export type { Folder, ItemMeta, ItemFull, StoredMessage, SpecialUse } from './store/mailstore.js';
export { Directory } from './directory.js';
export type { AuthUser, Role, Resolution } from './directory.js';
export { Delivery } from './delivery.js';
export { MailEvents } from './events.js';
export { parseMessage } from './mime/mime.js';
export { Settings, SECURITY_DEFAULTS } from './settings.js';
export type { SecuritySettings } from './settings.js';
export { IpPolicy, parseCidr } from './ippolicy.js';
export type { IpScope } from './ippolicy.js';
export { AuditLog, redact } from './audit.js';
export type { AuditEntry } from './audit.js';
export { SecretBox, loadSecretBox, createMasterKey } from './secrets.js';
export { UNLIMITED_LICENSE, LicenseLimitError, assertSeatAvailable, licensedUserCount } from './license-gate.js';
export type { LicenseGate, LicenseMode } from './license-gate.js';
export { resolveRelay, createTransport, relayTargetFromRow } from './relay.js';
export type { RelayTarget } from './relay.js';
export { splitAddress } from './directory.js';
export type { AuthFailure } from './directory.js';
export * as db from './db.js';
export { hashPassword, verifyPassword } from './password.js';
export { parseMessage as parseMime } from './mime/mime.js';
export { buildDsn, enhancedStatus } from './dsn.js';
export type { DsnFailure } from './dsn.js';
export { raiseAlert, resolveAlert } from './alerts.js';
export type { AlertSeverity } from './alerts.js';
export type { Db, Queryable } from './db.js';
export { fetchAccount, testExternalAccount, imapClient, classifyImapError, QuotaFullError, FetchError } from './fetch/fetch.js';
export type { ExternalAccount, FetchResult, TestResult } from './fetch/fetch.js';
export { Pop3Client } from './fetch/pop3-client.js';
export { IpcServer, ipcToken, attachIpcPublisher, subscribeIpcStream } from './ipc.js';
export { MailFlow } from './mailflow.js';
export * from './rules/model.js';
export { RuleMessage, planDelivery, ruleMatches, evaluateCondition } from './rules/engine.js';
export type { StoredRule, DeliveryPlan, Direction } from './rules/engine.js';
export { Archiver, ARCHIVE_DEFAULTS } from './archive/archive.js';
export type { ArchivePolicy } from './archive/archive.js';
export { indexPending, fulltextQuery } from './archive/search-index.js';
export { purgeArchive, purgeMailboxFolders, collectGarbage, pruneHousekeeping } from './archive/maintenance.js';
export { runBackup, verifyBackup, readManifest, backupChain, BACKUP_FORMAT } from './backup/backup.js';
export type { BackupManifest, BackupResult, VerifyResult } from './backup/backup.js';
export { restoreFull, restorePartial } from './backup/restore.js';
export type { PartialScope, PartialResult, FullRestoreResult } from './backup/restore.js';
export { performBackup, checkTarget, targetPath, verifyLatestBackups, checkBackupFreshness, materializeRun, isRemoteTarget } from './backup/service.js';
export type { BackupTargetRow, RemoteEncryption } from './backup/service.js';
export { encryptStream, decryptStream, newEncryption, keyFromInfo, encryptedSize } from './backup/crypt.js';
export { openRemote, isRemoteKind } from './backup/remote.js';
export type { S3Config, FtpConfig, RemoteStore } from './backup/remote.js';
export { enqueueJob, jobStatus } from './jobs.js';
export type { EnqueueOptions } from './jobs.js';
export { exportMessages, toMboxEntry, EXPORT_LIMIT } from './archive/export.js';
export { tableRows as readBackupTable } from './backup/restore.js';
export * from './control.js';
export * from './install.js';
export { loadTls, generateSelfSigned, describeCert, installCertificate } from './tls.js';
export type { CertInfo } from './tls.js';
export * from './updates.js';
export * from './monitor.js';
export { ConnectionLimiter, DEFAULT_LIMITS } from './connlimit.js';
export type { ConnectionLimits } from './connlimit.js';
export * from './hardening.js';
