#!/usr/bin/env node
// Regenerates db/schema.sql (fresh-install schema) from db/migrations/NNN_*.sql.
// Fresh installs run schema.sql once, then the migration runner records every
// listed version in schema_migrations so later upgrades apply only newer files.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const migDir = join(root, 'db', 'migrations');
const files = readdirSync(migDir).filter((f) => /^\d{3}_[a-z0-9_]+\.sql$/.test(f)).sort();

const seen = new Set();
const parts = [];
const manifest = [];
for (const f of files) {
  const version = Number(f.slice(0, 3));
  if (seen.has(version)) throw new Error(`Duplicate migration number ${version} (${f})`);
  seen.add(version);
  const sql = readFileSync(join(migDir, f), 'utf8');
  manifest.push({ version, file: f, sha256: createHash('sha256').update(sql).digest('hex') });
  parts.push(`-- >>> ${f}\n${sql.trim()}\n-- <<< ${f}\n`);
}

const header =
  '-- GENERATED by scripts/build-schema.mjs — DO NOT EDIT.\n' +
  '-- Edit db/migrations/NNN_*.sql and re-run `npm run db:schema`.\n' +
  `-- Includes migrations: ${manifest.map((m) => m.version).join(', ')}\n\n`;

writeFileSync(join(root, 'db', 'schema.sql'), header + parts.join('\n'));
writeFileSync(join(root, 'db', 'schema.manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
console.log(`schema.sql built from ${files.length} migration(s).`);
